#!/bin/bash

echo $#
echo $*

#select i in "a" "b" "c" "d"; do
#break
#done
#echo "You select:  " $i
echo "input your choice: "
read var
case $var in 
    1) echo "case1";;
    2) echo "case2";;
    3) echo "case3";;
    *) echo "pls input 1,2,3"
esac

#for i in {1..100}; do
#echo $i
#done
